### PR TITLE
wifi: scan: Fix scan results display

### PR DESCRIPTION
**Pull request by D-Triveni**
As scan results are getting dropped, replaced printk with printf

### CODE REVIEW

**Review by krish2718 — COMMENTED** [review]
There shouldn't be any difference b/w printk/printf in terms of buffering? Can you please share why the results are being dropped? This typically happens with LOG_* macros.

**Comment by D-Triveni** [comment]
> There shouldn't be any difference b/w printk/printf in terms of buffering? Can you please share why the results are being dropped? This typically happens with LOG_* macros.

I don't find any reason why printk() is dropping messages. But even after replacing whole logger module with printk, still messages are getting dropped.

**Comment by D-Triveni** [comment]
@krish2718  
By adding some delay ( k_msleep(150)) in the scan results handler, message are not dropped with printk.

**Comment by krish2718** [comment]
> > There shouldn't be any difference b/w printk/printf in terms of buffering? Can you please share why the results are being dropped? This typically happens with LOG_* macros.
> 
> I don't find any reason why printk() is dropping messages. But even after replacing whole logger module with printk, still messages are getting dropped.

Can you please share those logs?

**Comment by D-Triveni** [comment]
> > > There shouldn't be any difference b/w printk/printf in terms of buffering? Can you please share why the results are being dropped? This typically happens with LOG_* macros.
> > 
> > 
> > I don't find any reason why printk() is dropping messages. But even after replacing whole logger module with printk, still messages are getting dropped.
> 
> Can you please share those logs?

Scan requested
46   | Wi-Fi-5.9.1_80                   14    | 44   | -65  | Open     | 00:0F
--- 70 messages dropped ---

**Comment by krish2718** [comment]
> > > > There shouldn't be any difference b/w printk/printf in terms of buffering? Can you please share why the results are being dropped? This typically happens with LOG_* macros.
> > > 
> > > 
> > > I don't find any reason why printk() is dropping messages. But even after replacing whole logger module with printk, still messages are getting dropped.
> > 
> > 
> > Can you please share those logs?
> 
> Scan requested 46 | Wi-Fi-5.9.1_80 14 | 44 | -65 | Open | 00:0F --- 70 messages dropped ---

Ah, `CONFIG_LOG_PRNITK` is enabled by default, so, `printk` is buffered, please disable that and try for unbuffered prints.

**Comment by D-Triveni** [comment]
> > > > > There shouldn't be any difference b/w printk/printf in terms of buffering? Can you please share why the results are being dropped? This typically happens with LOG_* macros.
> > > > 
> > > > 
> > > > I don't find any reason why printk() is dropping messages. But even after replacing whole logger module with printk, still messages are getting dropped.
> > > 
> > > 
> > > Can you please share those logs?
> > 
> > 
> > Scan requested 46 | Wi-Fi-5.9.1_80 14 | 44 | -65 | Open | 00:0F --- 70 messages dropped ---
> 
> Ah, `CONFIG_LOG_PRNITK` is enabled by default, so, `printk` is buffered, please disable that and try for unbuffered prints.

Tried by disabling `CONFIG_LOG_PRNITK`, logging is proper now.

**Comment by D-Triveni** [comment]
Closing here, raising another PR for nrfconnect/sdk-nrf

**Pull request closed without merging**
